@extends('web.template.master')

{{-- Content --}}
@section('content')
    <!--====== PREALOADER PART START ======-->
    <div class="preloader">
        <div class="thecube">
            <div class="cube c1"></div>
            <div class="cube c2"></div>
            <div class="cube c4"></div>
            <div class="cube c3"></div>
        </div>
    </div>

    <section id="page-banner" class="pt-70 pb-0">
        <div class="banner-inner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="page-banner-content text-right">
                            <a href="">Home</a>
                            <h3>Terms and Conditions</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="pb-70">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title para">
                        <div class="text-center">
                            <h3>Terms and Conditions!</h3>
                            <ul>
                                <li></li>
                                <li></li>
                                <li></li>
                                <li></li>
                                <li></li>
                            </ul>
                        </div>
                        <p>These general terms of use (the "General Terms of Use") describe the terms on which the Users (defined hereunder) access, view, use and register on the Android app & Pyaas.in and any mobile or other application owned and/or operated
                            by Pyaas or any of its Affiliates (defined hereinafter) ("Pyaas"), collectively referred to as the "Platform" Pyaas adheres strictly to the Information Technology Act, 2000 (hereinafter referred to as the "IT Act, 2000") and the
                            rules framed there under. In order to ensure compliance with the above, Pyaas records that this document is an electronic record generated by a computer system and [does not require any physical or digital signatures]. Pyaas has
                            established these General Terms of Use in order to inter alia ensure compliance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. PLEASE READ THESE GENERAL TERMS OF USE CAREFULLY
                            BEFORE ACCESSING, VIEWING, USING OR REGISTERING ON THE PLATFORM OR ACCESSING ANY MATERIAL, INFORMATION OR SERVICES THROUGH THE PLATFORM. USER'S ACCESS OR USE OF THE PLATFORM SHALL SIGNIFY USER'S UNCONDITIONAL ACCEPTANCE OF THE
                            GENERAL TERMS OF USE AND USER'S AGREEMENT TO BE LEGALLY BOUND BY THE SAME. Your access or use of the Platform is governed by these General Terms of Use. If you transact on the Platform, You shall be subject to the policies that
                            are applicable to the Platform for such a transaction. As long as you comply with these General Terms of Use, We grant you a non-exclusive, non-transferable, revocable and limited license to access and use the Platform.</p>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>1.Definitions</h6>
                            <p>The following defined terms shall have the meanings set out below, unless otherwise specified:</p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>"Affiliate" shall mean any person, directly or indirectly, controlling, controlled by, or under common control with Pyaas.The term "control" shall include the right to appoint the majority of the directors or to
                                                control the management/ policy decisions exercisable by any person(s) acting individually.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon">
                                        <i class="fa fa-circle"></i>
                                    </div>
                                    <div class="cont pl-15">
                                        <p> "Products" shall mean the Drinking water cans which is listed and delivered by Pyaas on the Platform.</p>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon">
                                        <i class="fa fa-circle"></i>
                                    </div>
                                    <div class="cont pl-15">
                                        <p> "We", "Us" and "Our" shall mean Pyaas.</p>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon">
                                        <i class="fa fa-circle"></i>
                                    </div>
                                    <div class="cont pl-15">
                                        <p>"You", "Your", "Yourself" or "User" refers to a buyer, or any visitor on the Platform.</p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>2.Account and Registration</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You are encouraged to register on the Platform by creating an Account (as defined below), and providing such other details as necessary, including Phone number (OTP verification) your name (or the name of your business
                                                entity, as the case may be), address, email address.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>In order to order water can, You must register with your mobile number on the Platform and create an account on the Platform, with a unique user identity and password (hereinafter referred to as "Account"). You
                                                may continue to order water until such time that you are registered on the Platform. You are responsible for maintaining the confidentiality of Your Account and the related details, and for restricting access
                                                to your computer and other electronic devices to prevent unauthorized access to Your Account. You agree to accept responsibility for all activities that occur under and in relation to Your Account (with or without
                                                your consent), and agree that Pyaas shall not be liable in any manner whatsoever. You agree to notify us immediately if you have any reason to believe that Your Account information has become known to anyone
                                                else, or if the Account is being, or is suspected of being, used in an unauthorized manner. You must ensure that you exit from Your Account at the end of each session. You may be held liable for losses incurred
                                                by Pyaas or any other User of the Platform due to any authorized or unauthorized use of Your Account for any reason attributable to You.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You shall not have more than 1 (one) active Account on the Platform at any point of time. Use of another User's Account information is expressly prohibited. You are also prohibited from transferring Your Account
                                                to another party.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You agree that if You provide any information which is untrue, inaccurate or incomplete, or if We have reasonable grounds to suspect that such information is untrue, inaccurate or incomplete, or if such information
                                                is not in accordance with these General Terms of Use, We shall have the right to indefinitely suspend, terminate or block You from accessing and using the Platform, and take such other action as We deem fit.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You agree that if You provide any information which is untrue, inaccurate or incomplete, or if We have reasonable grounds to suspect that such information is untrue, inaccurate or incomplete, or if such information
                                                is not in accordance with these General Terms of Use, We shall have the right to indefinitely suspend, terminate or block You from accessing and using the Platform, and take such other action as We deem fit.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must also inform us immediately in the event of any change in the information provided by you. You can also update the Account related information provided by you, by visiting the appropriate section in the
                                                app]. Pyaas reserves the right to restrict/ prohibit your access to the Platform and terminate your registration, at any time, without according any reason for doing so.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>3.Eligibility</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>The use of the Platform is available only to persons who can enter into legally binding contracts under the Indian Contract Act, 1872. If you are a minor i.e. under the age of 18 (eighteen) years, you shall not
                                                register yourself as a User on the Platform or transact on the Platform. You represent that you are of legal age to form a binding contract, and are not a person barred from purchasing Products on the Platform
                                                under the applicable laws.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must have the requisite resources, including internet access and equipment to access and use the Platform, and Pyaas shall not be liable or responsible for the same.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>4.Obligations of Users</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use the Platform in any way that causes, or is likely to cause, the Platform or the access thereto to be interrupted, damaged or impaired in any way. You understand that you, and not Paanilao, are responsible
                                                for all electronic communications and content sent from your computer or other equipments and Your Account and You must use the Platform for lawful purposes only.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use the Platform to publish or share any material without having the right to do so;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use the Platform to host, display, upload, modify, publish, transmit, update, share, send, use or reuse any material/information that does not belong to You and You do not have any right to; or which
                                                is grossly harmful, illegal, offensive (including but not limited to material that is sexually explicit content or which promotes racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent,
                                                harassing, blasphemous, defamatory, libelous, obscene, pornographic, paedophilic or menacing; ethnically objectionable, hateful or racial, disparaging or in breach of any intellectual property including, but
                                                not limited to, patent, trademark, copyright or other proprietary rights, confidentiality, privacy or any other proprietary right/ information; or is otherwise injurious to third parties; or relates to or promotes
                                                money laundering or gambling; or is harmful to minors in any way; or impersonates another person; or threatens the unity, integrity, defence, security or sovereignty of India or its friendly relations with foreign
                                                states or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation; or which is otherwise unlawful in any manner whatsoever; or
                                                which consists of or contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or which deceives or misleads
                                                the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature.
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use the Platform for fraudulent purposes, or in connection with any criminal offense or other unlawful activity;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use the Platform to cause any commercial solicitation, chain letters, mass mailings or any 'spam' to cause annoyance, inconvenience or needless anxiety; or</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use the Platform to impersonate another person, or to deceive any other person about the origin of any communication, which is offensive.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You may send communications; and submit suggestions, ideas, comments, questions or other information, as long as the content is in compliance with these General Terms of Use.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You must not use any false e-mail address, impersonate any person or entity, or otherwise mislead any person as to the origin of any content. We reserve the right (but not the obligation) to remove or delete any
                                                such content that, in the sole judgment of Pyaas, violates these General Terms of Use and/or terminate your right to access or use the Platform.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>5.Representations and Warranties of the Users</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>By visiting, viewing, accessing, installing, loading or using the Platform, You are providing unqualified acceptance to these General Terms of Use and any and all policies of Pyaas relating to the Platform;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You are of legal age and sound mind, and have accepted these General Terms of Use, without any undue force, pressure, influence or coercion;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>By using the Platform, You are not violating any other terms, conditions or agreement to which You may be subject, and any law applicable to You;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You own or otherwise control all of the rights to the content that You post or that You otherwise provide on or through the Platform;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You shall use the Platform only for lawful purposes;</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15 ">
                                            <p>As on the date that the content or material is submitted to Pyaas:</p>
                                            <div class="d-flex">
                                                <div class="icon">
                                                    <i class="fa fa-circle-o "></i>
                                                </div>
                                                <div class="cont pl-15">
                                                    <p class="pt-1">the content and material is accurate; </p>
                                                </div>
                                            </div>
                                            <div class="d-flex">
                                                <div class="icon">
                                                    <i class="fa fa-circle-o "></i>
                                                </div>
                                                <div class="cont pl-15">
                                                    <p class="pt-1">use of the content and material supplied by You does not breach any applicable policies of Pyaas or any applicable law, and</p>
                                                </div>
                                            </div>
                                            <div class="d-flex">
                                                <div class="icon">
                                                    <i class="fa fa-circle-o "></i>
                                                </div>
                                                <div class="cont pl-15">
                                                    <p class="pt-1"> the use of the content and material will not cause injury to any person or entity.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>6.THIRD-PARTY SERVICES</h6>
                            <p class=""></p>
                            <p>
                                In general, the third-party providers used by us will only Deliver water cans, collect, and disclose your information to the extent necessary to allow them to perform the services they provide to us.
                            </p>
                            <p>
                                However, certain third-party service providers, such as payment gateways and other payment transaction processors, have their own privacy policies in respect to the information we are required to provide to them for your purchase-related transactions.
                            </p>
                            <p>
                                For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.
                            </p>
                            <p>
                                In particular, remember that certain providers may be located in or have facilities that are located a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider,
                                then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.
                            </p>
                            <p>
                                Once you leave our App (Pyaas) or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy Terms of Service.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>7. Feedbacks and Reviews</h6>
                            <p class="pt-25"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>
                                                You may provide feedback in relation to the use of the Platform and Products. You agree to provide honest feedback, review and comments, and support the same with sufficient evidence as required by us.
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You are not in breach of any obligation (legal, contractual or otherwise) by sharing such feedback with us, and that you are not entitled to any compensation for provision of such feedback.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p> When You provide any feedback on the Platform, You grant to Pyaas, a non-exclusive, royalty-free, worldwide, transferable, irrevocable, perpetual and unconditional license to </p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="cont pl-15">
                                            <div class="d-flex">
                                                <div class="icon">
                                                    <i class="fa fa-circle-o "></i>
                                                </div>
                                                <div class="cont pl-15">
                                                    <p class="pt-1">use, and share Your feedback as We deem fit, including to the User to whom such feedback relates; and </p>
                                                </div>
                                            </div>
                                            <div class="d-flex">
                                                <div class="icon">
                                                    <i class="fa fa-circle-o "></i>
                                                </div>
                                                <div class="cont pl-15">
                                                    <p class="pt-1"> remove whole or part of the feedback, which We may consider to be defamatory, in breach of applicable laws or these General Terms of Use.</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>8.Termination</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>
                                                You shall, at all times, be bound by these General Terms of Use. You may however choose to terminate your arrangement under these General Terms of Use by closing Your Account, and thereafter ceasing to use the Platform.
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Paanilao reserves a right to forthwith terminate Your arrangement (without any liability) under these General Terms of Use, without notice to You, if: a) You breach any of these General Terms of Use; b) Such termination
                                                is required under any applicable law; and c) For any other reason, as Paanilao may deem fit.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Paanilao may also block your future access/ use of the Platform. In addition, you also agree that any violation of these General Terms of Use by You will cause irreparable harm to Paanilao, for which monetary damages
                                                may be inadequate. You therefore agree that Paanilao is entitled to any injunctive or other equitable relief as may be applicable. These remedies are in addition to any other remedies that Paanilao may have
                                                at law or in equity.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>In the alternative, Paanilao may choose to temporarily suspend access to the Platform, and/or Your Account for any breach of these General Terms of Use.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>In case of any termination, you shall immediately fulfill your pending obligations/ liabilities towards Paanilao and/or any other User, resulting from use of the Platform.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>9.Water Cans Deposit</h6>
                            <p class="p-2"></p>
                            <p>Water Cans deposit collected Pyaas and Customer, therefore, Pyaas is liable to charge or deposit any taxes applicable on such transaction. In the event of discontinuation of service from Pyaas, Customer have to contact the pyaas
                                for the refund, Pyaas assist you to the best of our abilities by providing relevant information to you, how to proceed.Customer is liable for return /exchange of water cans in the condition they received during delivery, if
                                failed to meet the terms result in pay the deposit for the new water.</p>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>10.Delivery Policy</h6>
                            <p class="p-2"></p>
                            <p>Pyaas aim to deliver the water cans with best in effort to delivery on the time slot selected by customers on the time of delivery. Changing of delivery time slot is not permitted after the order is confirmed.</p>
                            <p>At present Pyaas provide two convenient slots</p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Morning: 9 AM to 01 PM</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Evening: 3 PM to 7 PM.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                            <p>Please note that the delivery slot is changeable by Pyaas </p>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>11.Amendment to the General Terms of Use</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Your use of and access to the Platform is offered on the condition that You unconditionally accept all the terms and conditions provided in these General Terms of Use, along with any amendments made by Pyaas at
                                                its sole discretion, from time to time, and posted on the Platform. Pyaas shall not be required to notify you, whether as a registered User or not, of any changes made to these General Terms of Use.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Once the revised General Terms of Use are made available on the Platform, Your continued use of the Platform shall be construed to be your deemed acceptance of the revised General Terms of Use. Please regularly
                                                visit the Platform to view the most current General Terms of Use, which can be determined by the "Last Updated" legend above.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>12.Miscellaneous</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Severability: - If any provision contained in these General Terms of Use is deemed void, invalid or unlawful, such a provision shall be deemed severable from the remaining terms hereunder, which remaining terms
                                                will continue in full force and effect.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Force Majeure: - Pyaas will not be held responsible for any delay or failure to comply with our obligations hereunder, if the delay or failure arises from any cause which is beyond our reasonable control.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Waiver: - If you breach these General Terms of Use and if we do not take any action, it does not mean that we have waived our rights and remedies hereunder or under any applicable laws. Any waiver shall be deemed
                                                effective only when made in writing.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Assignment: - You cannot assign or otherwise transfer any of your rights/ obligations under General Terms of Use to any third party. Pyaas may however freely transfer the same to any third party, without your consent.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Relationship between Pyaas and You: - Pyaas and You are independent parties, and nothing in these General Terms of Use will be construed to create a partnership, joint venture, agency, franchise, or employment relationship
                                                between the parties. You will have no authority to make or accept any offers or representations on our behalf. You will not make any statement that would contradict anything in this Clause. These General Terms
                                                of Use will not create an exclusive relationship between you and us.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Governing Law and Jurisdiction: - These General Terms of Use shall be governed by the laws of India. Any disputes arising out of or in relation to these General Terms of Use, or any transactions entered into on
                                                or through the Platform or the relationship between You and Pyaas, shall be subject to the exclusive jurisdiction of the Courts in Guwahati.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Notices: For any queries relating to the Platform, You can reach out to us at contact-us.</p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>13.Additional Terms of Use</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Pyaas only Creates the Platform to the Service Provider and its Agents for selling the water cans through its platform (Pyaas Delivery app) to the consumers.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Pyaas is not responsible for causing any delay in case of Delivery of Water cans within the delivery slot requested by you, at the time of placing order. It may get delayed due to various reasons for example extreme
                                                weather condition and govt. Rules which is beyond human control.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Re-arrange the delivery time will be done as early as possible.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Pyaas is not liable for any kind of illegal, offensive deceptive, misleading, abusive, indecent, harassing, blasphemous, defamatory, libelous, obscene, paedophilic or menacing, ethnically objectionable, disparaging,
                                                or otherwise any activity injurious or harming to the consumers in any way arising out Delivery of water cans by its Service Providers and its Agents.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Paanilao is not responsible for delivery of the Water cans, if it is not in good condition, delivered by its supplier/service provider or its agent and it is the sole responsibility of the supplier for delivery
                                                the product (water can) with his own / self-appointed delivery vehicle.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>You are supposed to keep the water cans in a good condition for other companies to take it back at the time of ordering the next water can. An additional charge are applied for the delivery of water cans on higher
                                                floors that do not have elevator facilities. These charges are to be paid by you as per the suppliers norms.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>
                                                <strong> Food Safety and Standards Act, 2006</strong>: It is hereby clarified by Paanilao that the liability of any violation of the Food Safety and Standards Act, 2006 and applicable rules and regulations made
                                                thereunder shall solely rest with the supplier/service provider or its agent and brand of any nature, in such as may be defined under the Food Safety and Standards Act, 2006 from time to time.
                                            </p>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-45">
                            <h6>14.Cancellation & Refund Policy</h6>
                            <p class="p-2"></p>
                            <ul>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>Order once delivered and after receiving of cans, there will be no cancellation or refund of the water cans.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>After placement of order, and order confirmation. User can request for cancellation before the delivery via app or via calling to customer support 90000-1111 or via whats app or via email at info@pyaas.in</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>
                                                There will be refund for the can deposit amount, if the cans are purchased from Pyaas. There will be full refund of amount with a condition that can is not damaged or does not has leakage.
                                            </p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="d-flex">
                                        <div class="icon">
                                            <i class="fa fa-circle"></i>
                                        </div>
                                        <div class="cont pl-15">
                                            <p>
                                                Refund will be made to the customer within 3 working days.
                                            </p>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </div>

                    <div class="col-lg-12">
                        <div class="contact-info pt-25">
                            <h6>15.Membership policies</h6>
                            <p class=""></p>
                            <p>
                                If you wish to cancel the membership, you may do so before your order is delivered for the first time.
                            </p>
                            <p>
                                In case you might remain absent in your location at the time we deliver your order, you need to inform us beforehand about your absence. If our delivery executive is already out for delivery into your location with any knowledge of your absence then a
                                jar for the day will be deducted from your account even if you do not receive it.
                            </p>
                            <p>
                                Brands cannot be changed after your membership is confirmed. However you can always feel free to contact our customer care for any assistance.
                            </p>
                            <p>
                                Delivery slots cannot be changed. However you can call the support if you want get your order delivered on a different slot. This facility is available only for that specific day and will not be entertained in the following days.
                            </p>
                            <p>
                                Delivery frequency cannot be changed.<br> Refund option is available only if you cancel your membership before your oder is delivered for the first time.<br> Quantity cannot be changed under any circumstances.
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="contact-info pt-25">
                            <h6>16. Single orders</h6>
                            <p class=""></p>
                            <p>
                                You may cancel your order only before your order is out for delivery.
                            </p>
                            <p>
                                Refund is available if order is cancelled before dispatching in 7-10 days.
                            </p>
                            <p>
                                Brand cannot be changed after placement of orders.
                            </p>
                            <p>
                                You can change the time slot before your order is dispatched.
                            </p>
                        </div>
                        <div class="contact-info pt-25">
                            <h6>17. Delivery</h6>
                            <p class=""></p>
                            <p>
                                At any point of time, to ensure sanity and security our delivery partners will not enter your house to delivery your order.</p>
                            <p>
                                Delivery is chargeable from third floor onwards @ Rs 5 per jar. However in case lift or elevator facility is available then it is not chargeable in case of upper floors.</p>
                        </div>
                        <div class="contact-info pt-25">
                            <h6>18. Bulk orders</h6>
                            <p class=""></p>
                            <p>
                                If you order 20 litres jar or above you need to pay a security deposit for the jars which will be refunded at the time of delivery. Additionally if you already have the exact amount of empty jars as you ordered then no security deposit is required.
                            </p>
                            <p>
                                For confirmation of bulk orders you need to pay us in advance and for this you need to call our customer care.
                            </p>
                            <p>
                                In bulk orders the order need to be cancelled before 24 hours for availing full refund.
                            </p>
                            <p>
                                If you cancel your order after it has been already dispatched the 50% of the payment already made by you , whatever amount it may be will be withheld and 50% will be refunded.
                            </p>
                            <p>
                                You can change the brand, time slot and quantity before your order is dispatched.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

{{-- Script --}}
@section('script')
@endsection